# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkD-Oug7os4gsZ_rS_V_6yqU1rKbGgHC
"""

import gradio as gr
import pickle
import pandas as pd

model = pickle.load(open('log_reg_model.pkl', 'rb'))

def predict(age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal):
  data = {
      "age" : age,
      "sex" : sex,
      "cp" : cp,
      "trestbps" : trestbps,
      "chol" : chol,
      "fbs" : fbs,
      "restecg" : restecg,
      "thalach" : thalach,
      "exang" : exang,
      "oldpeak" : oldpeak,
      "slope" : slope,
      "ca" : ca,
      "thal" : thal,
  }
  df = pd.DataFrame([data])
  pred = model.predict(df)
  if pred==1:
    return "You have a heart disease."
  else: return "You don't have a heart disease"

inputs = [
    gr.Number(label="Age"),
    gr.Radio(["Male", "Female"], label="Sex", type="index"),  # 0 = Male, 1 = Female
    gr.Radio([0, 1, 2, 3], label="Chest Pain Type (0-3)"),
    gr.Number(label="Resting BP"),
    gr.Number(label="Cholesterol"),
    gr.Checkbox(label="Fasting Blood Sugar > 120 mg/dl"),
    gr.Radio([0, 1, 2], label="Rest ECG (0 - Nothing to note, 1 - Wave abnormality in ST-T , 2 -  Possible or definite left ventricular hypertrophy)"),
    gr.Number(label="Max Heart Rate"),
    gr.Checkbox(label="Exercise-induced Angina"),
    gr.Number(label="Oldpeak"),
    gr.Radio([0, 1, 2], label="Slope of ST segment"),
    gr.Slider(0, 3, step=1, label="Number of Major Vessels clored by flouroscopy"),
    gr.Radio([0, 1, 2], label="Thal (0 = normal, 1 = fixed defect, 2 = reversable defect)")
]

interface = gr.Interface(fn=predict,
                         inputs=inputs,
                         outputs="text",
                         title="Heart Disease Predictor")

interface.launch()